
# File: makefile
# Author: Ramon de Araujo Borba < ramonborba97@gmail.com >
# Institution: UFSC
# Date: 31/12/2021
# Description: makefile for CShape3d assignment

# Compiler
CC=g++

# Source files
SRCS=testCShape3d.cpp

# Output
OUTPUT=app.out

defaut: $(OUTPUT)

$(OUTPUT): $(SRCS)
	$(CC) $^ -o $@

clean:
	rm $(OUTPUT)